apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::100807321073:role/UdacityFlaskDeployCBKubectlRole
      username: build 
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::100807321073:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-13N3B02TGNKDN
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-03-04T16:35:22Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl
    operation: Update
    time: "2021-03-04T16:35:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2025"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: d75d0395-9b9a-4195-a9fd-d1a5595f35ce
